# Generated by Django 3.2.6 on 2021-08-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('resume_portfolio_link', models.URLField()),
                ('primary_skills', models.CharField(max_length=200)),
                ('secondary_skills', models.CharField(max_length=200)),
                ('candidate_experince', models.IntegerField()),
            ],
        ),
    ]
