# Generated by Django 3.2.6 on 2021-08-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_app', '0002_rename_name_document_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user_id',
            new_name='user',
        ),
    ]
