# Generated by Django 3.2.6 on 2021-08-31 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_app', '0003_rename_user_id_document_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='name',
        ),
    ]
